# Site settings
title: Alejandro Fontán
description: 'Afontan'
url: 'https://devee.com.ar'
baseurl: ''
profilepic: '/images/tzuehlke.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Alejandro Fontán'
  email: alejandro@devee.com.ar
  twitter_username: a_fontan
#  facebook_username: joshgerdes
  github_username:  afontan
  linkedin_username:  alejandro-fontán-bab6b260

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
